# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-09-06 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(default=None, max_length=200)),
                ('is_used', models.IntegerField(default=0)),
                ('admin_level', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('neighborhood', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('is_active', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='generic_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('push_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('birthdate', models.DateTimeField(default=datetime.datetime.now)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(default=None, max_length=200)),
                ('email_activated', models.IntegerField(default=0)),
                ('phone_activated', models.IntegerField(default=0)),
                ('facebook_profile', models.CharField(default='', max_length=400)),
                ('admin_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='receptivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residue_id', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(default=0)),
                ('minimun', models.IntegerField(default=0)),
                ('maximun', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residue_name', models.CharField(max_length=200)),
                ('unity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('member_id', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
